### PR TITLE
allow for custom IP source (work around for ipaddr.de being down)

### PR DESCRIPTION
**Pull request by mihasya**

### CODE REVIEW

**Comment by slot** [comment]
Thank you for your commit. Could you please remove the debug output in updater.py (lines 100, 103 and 104) before I pull. Thx!

**Comment by slot** [comment]
Oh and could you add it to the config file with some documentation. As this is an optional parameter please comment it out by default. Also I would let the user know that our script now takes the first IP on the response no matter if it is the right one. Thx!

**Comment by mihasya** [comment]
All reasonable, please hold :) I thought I'd gotten all the prints, my bad.

**Comment by mihasya** [comment]
Thanks!

**Pull request merged**
